# 如果不配置会默认使用spring security提供的默认clientid 和 clientsecret
merryyou:
  security:
    oauth2:
      storeType: jwt
      jwtSigningKey: merryyou
      clients[0]:
        clientId: merryyou
        clientSecret: merryyou
      clients[1]:
        clientId: merryyou1
        clientSecret: merryyou1

server:
  session:
    timeout: 60
  port: 9090

spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
logging:
  level: debug